//The list of options for the react-select component in the Lookup Attachment row in UploadAttachments.js.
const options = [
    { value: "http://edamontology.org/format_1196", label: "SMILES" },
    { value: "http://edamontology.org/format_1197", label: "InChI" },
    { value: "http://edamontology.org/format_1198", label: "mf" },
    { value: "http://edamontology.org/format_1199", label: "InChIKey" },
    { value: "http://edamontology.org/format_1200", label: "smarts" },
    { value: "http://edamontology.org/format_1206", label: "unambiguous pure" },
    { value: "http://edamontology.org/format_1207", label: "nucleotide" },
    { value: "http://edamontology.org/format_1208", label: "protein" },
    { value: "http://edamontology.org/format_1209", label: "consensus" },
    { value: "http://edamontology.org/format_1210", label: "pure nucleotide" },
    { value: "http://edamontology.org/format_1211", label: "unambiguous pure nucleotide" },
    { value: "http://edamontology.org/format_1212", label: "dna" },
    { value: "http://edamontology.org/format_1213", label: "rna" },
    { value: "http://edamontology.org/format_1214", label: "unambiguous pure dna" },
    { value: "http://edamontology.org/format_1215", label: "pure dna" },
    { value: "http://edamontology.org/format_1216", label: "unambiguous pure rna sequence" },
    { value: "http://edamontology.org/format_1217", label: "pure rna" },
    { value: "http://edamontology.org/format_1218", label: "unambiguous pure protein" },
    { value: "http://edamontology.org/format_1219", label: "pure protein" },
    { value: "http://edamontology.org/format_1248", label: "EMBL feature location" },
    { value: "http://edamontology.org/format_1295", label: "quicktandem" },
    { value: "http://edamontology.org/format_1296", label: "Sanger inverted repeats" },
    { value: "http://edamontology.org/format_1297", label: "EMBOSS repeat" },
    { value: "http://edamontology.org/format_1316", label: "est2genome format" },
    { value: "http://edamontology.org/format_1318", label: "restrict format" },
    { value: "http://edamontology.org/format_1319", label: "restover format" },
    { value: "http://edamontology.org/format_1320", label: "REBASE restriction sites" },
    { value: "http://edamontology.org/format_1332", label: "FASTA search results format" },
    { value: "http://edamontology.org/format_1333", label: "BLAST results" },
    { value: "http://edamontology.org/format_1334", label: "mspcrunch" },
    { value: "http://edamontology.org/format_1335", label: "Smith-Waterman format" },
    { value: "http://edamontology.org/format_1336", label: "dhf" },
    { value: "http://edamontology.org/format_1337", label: "lhf" },
    { value: "http://edamontology.org/format_1341", label: "InterPro hits format" },
    { value: "http://edamontology.org/format_1342", label: "InterPro protein view report format" },
    { value: "http://edamontology.org/format_1343", label: "InterPro match table format" },
    { value: "http://edamontology.org/format_1349", label: "HMMER Dirichlet prior" },
    { value: "http://edamontology.org/format_1350", label: "MEME Dirichlet prior" },
    { value: "http://edamontology.org/format_1351", label: "HMMER emission and transition" },
    { value: "http://edamontology.org/format_1356", label: "prosite-pattern" },
    { value: "http://edamontology.org/format_1357", label: "EMBOSS sequence pattern" },
    { value: "http://edamontology.org/format_1360", label: "meme-motif" },
    { value: "http://edamontology.org/format_1366", label: "prosite-profile" },
    { value: "http://edamontology.org/format_1367", label: "JASPAR format" },
    { value: "http://edamontology.org/format_1369", label: "MEME background Markov model" },
    { value: "http://edamontology.org/format_1370", label: "HMMER format" },
    { value: "http://edamontology.org/format_1391", label: "HMMER-aln" },
    { value: "http://edamontology.org/format_1392", label: "DIALIGN format" },
    { value: "http://edamontology.org/format_1393", label: "daf" },
    { value: "http://edamontology.org/format_1419", label: "Sequence-MEME profile alignment" },
    { value: "http://edamontology.org/format_1421", label: "HMMER profile alignment (sequences versus HMMs)" },
    { value: "http://edamontology.org/format_1422", label: "HMMER profile alignment (HMM versus sequences)" },
    { value: "http://edamontology.org/format_1423", label: "Phylip distance matrix" },
    { value: "http://edamontology.org/format_1424", label: "ClustalW dendrogram" },
    { value: "http://edamontology.org/format_1425", label: "Phylip tree raw" },
    { value: "http://edamontology.org/format_1430", label: "Phylip continuous quantitative characters" },
    { value: "http://edamontology.org/format_1432", label: "Phylip character frequencies format" },
    { value: "http://edamontology.org/format_1433", label: "Phylip discrete states format" },
    { value: "http://edamontology.org/format_1434", label: "Phylip cliques format" },
    { value: "http://edamontology.org/format_1435", label: "Phylip tree format" },
    { value: "http://edamontology.org/format_1436", label: "TreeBASE format" },
    { value: "http://edamontology.org/format_1437", label: "TreeFam format" },
    { value: "http://edamontology.org/format_1445", label: "Phylip tree distance format" },
    { value: "http://edamontology.org/format_1454", label: "dssp" },
    { value: "http://edamontology.org/format_1455", label: "hssp" },
    { value: "http://edamontology.org/format_1457", label: "Dot-bracket format" },
    { value: "http://edamontology.org/format_1458", label: "Vienna local RNA secondary structure format" },
    { value: "http://edamontology.org/format_1475", label: "PDB database entry format" },
    { value: "http://edamontology.org/format_1476", label: "PDB" },
    { value: "http://edamontology.org/format_1477", label: "mmCIF" },
    { value: "http://edamontology.org/format_1478", label: "PDBML" },
    { value: "http://edamontology.org/format_1504", label: "aaindex" },
    { value: "http://edamontology.org/format_1551", label: "Pcons report format" },
    { value: "http://edamontology.org/format_1552", label: "ProQ report format" },
    { value: "http://edamontology.org/format_1582", label: "findkm" },
    { value: "http://edamontology.org/format_1627", label: "Primer3 primer" },
    { value: "http://edamontology.org/format_1628", label: "ABI" },
    { value: "http://edamontology.org/format_1629", label: "mira" },
    { value: "http://edamontology.org/format_1630", label: "CAF" },
    { value: "http://edamontology.org/format_1631", label: "EXP" },
    { value: "http://edamontology.org/format_1632", label: "SCF" },
    { value: "http://edamontology.org/format_1633", label: "PHD" },
    { value: "http://edamontology.org/format_1637", label: "dat" },
    { value: "http://edamontology.org/format_1638", label: "cel" },
    { value: "http://edamontology.org/format_1639", label: "affymetrix" },
    { value: "http://edamontology.org/format_1641", label: "affymetrix-exp" },
    { value: "http://edamontology.org/format_1644", label: "CHP" },
    { value: "http://edamontology.org/format_1665", label: "Taverna workflow format" },
    { value: "http://edamontology.org/format_1705", label: "HET group dictionary entry format" },
    { value: "http://edamontology.org/format_1734", label: "PubMed citation" },
    { value: "http://edamontology.org/format_1735", label: "Medline Display Format" },
    { value: "http://edamontology.org/format_1736", label: "CiteXplore-core" },
    { value: "http://edamontology.org/format_1737", label: "CiteXplore-all" },
    { value: "http://edamontology.org/format_1739", label: "pmc" },
    { value: "http://edamontology.org/format_1740", label: "iHOP format" },
    { value: "http://edamontology.org/format_1741", label: "OSCAR format" },
    { value: "http://edamontology.org/format_1861", label: "PlasMapper TextMap" },
    { value: "http://edamontology.org/format_1910", label: "newick" },
    { value: "http://edamontology.org/format_1911", label: "TreeCon format" },
    { value: "http://edamontology.org/format_1912", label: "Nexus format" },
    { value: "http://edamontology.org/format_1915", label: "Format" },
    { value: "http://edamontology.org/format_1919", label: "Sequence record format" },
    { value: "http://edamontology.org/format_1920", label: "Sequence feature annotation format" },
    { value: "http://edamontology.org/format_1921", label: "Alignment format" },
    { value: "http://edamontology.org/format_1923", label: "acedb" },
    { value: "http://edamontology.org/format_1925", label: "codata" },
    { value: "http://edamontology.org/format_1926", label: "dbid" },
    { value: "http://edamontology.org/format_1927", label: "EMBL format" },
    { value: "http://edamontology.org/format_1928", label: "Staden experiment format" },
    { value: "http://edamontology.org/format_1929", label: "FASTA" },
    { value: "http://edamontology.org/format_1930", label: "FASTQ" },
    { value: "http://edamontology.org/format_1931", label: "FASTQ-illumina" },
    { value: "http://edamontology.org/format_1932", label: "FASTQ-sanger" },
    { value: "http://edamontology.org/format_1933", label: "FASTQ-solexa" },
    { value: "http://edamontology.org/format_1934", label: "fitch program" },
    { value: "http://edamontology.org/format_1935", label: "GCG" },
    { value: "http://edamontology.org/format_1936", label: "GenBank format" },
    { value: "http://edamontology.org/format_1937", label: "genpept" },
    { value: "http://edamontology.org/format_1938", label: "GFF2-seq" },
    { value: "http://edamontology.org/format_1939", label: "GFF3-seq" },
    { value: "http://edamontology.org/format_1940", label: "giFASTA format" },
    { value: "http://edamontology.org/format_1941", label: "hennig86" },
    { value: "http://edamontology.org/format_1942", label: "ig" },
    { value: "http://edamontology.org/format_1943", label: "igstrict" },
    { value: "http://edamontology.org/format_1944", label: "jackknifer" },
    { value: "http://edamontology.org/format_1945", label: "mase format" },
    { value: "http://edamontology.org/format_1946", label: "mega-seq" },
    { value: "http://edamontology.org/format_1947", label: "GCG MSF" },
    { value: "http://edamontology.org/format_1948", label: "nbrf/pir" },
    { value: "http://edamontology.org/format_1949", label: "nexus-seq" },
    { value: "http://edamontology.org/format_1950", label: "pdbatom" },
    { value: "http://edamontology.org/format_1951", label: "pdbatomnuc" },
    { value: "http://edamontology.org/format_1952", label: "pdbseqresnuc" },
    { value: "http://edamontology.org/format_1953", label: "pdbseqres" },
    { value: "http://edamontology.org/format_1954", label: "Pearson format" },
    { value: "http://edamontology.org/format_1957", label: "raw" },
    { value: "http://edamontology.org/format_1958", label: "refseqp" },
    { value: "http://edamontology.org/format_1960", label: "Staden format" },
    { value: "http://edamontology.org/format_1961", label: "Stockholm format" },
    { value: "http://edamontology.org/format_1962", label: "strider format" },
    { value: "http://edamontology.org/format_1963", label: "UniProtKB format" },
    { value: "http://edamontology.org/format_1964", label: "plain text format (unformatted)" },
    { value: "http://edamontology.org/format_1966", label: "ASN.1 sequence format" },
    { value: "http://edamontology.org/format_1967", label: "DAS format" },
    { value: "http://edamontology.org/format_1968", label: "dasdna" },
    { value: "http://edamontology.org/format_1969", label: "debug-seq" },
    { value: "http://edamontology.org/format_1970", label: "jackknifernon" },
    { value: "http://edamontology.org/format_1972", label: "NCBI format" },
    { value: "http://edamontology.org/format_1973", label: "nexusnon" },
    { value: "http://edamontology.org/format_1974", label: "GFF2" },
    { value: "http://edamontology.org/format_1975", label: "GFF3" },
    { value: "http://edamontology.org/format_1978", label: "DASGFF" },
    { value: "http://edamontology.org/format_1979", label: "debug-feat" },
    { value: "http://edamontology.org/format_1982", label: "ClustalW format" },
    { value: "http://edamontology.org/format_1983", label: "debug" },
    { value: "http://edamontology.org/format_1984", label: "FASTA-aln" },
    { value: "http://edamontology.org/format_1985", label: "markx0" },
    { value: "http://edamontology.org/format_1986", label: "markx1" },
    { value: "http://edamontology.org/format_1987", label: "markx10" },
    { value: "http://edamontology.org/format_1988", label: "markx2" },
    { value: "http://edamontology.org/format_1989", label: "markx3" },
    { value: "http://edamontology.org/format_1990", label: "match" },
    { value: "http://edamontology.org/format_1991", label: "mega" },
    { value: "http://edamontology.org/format_1992", label: "meganon" },
    { value: "http://edamontology.org/format_1996", label: "pair" },
    { value: "http://edamontology.org/format_1997", label: "PHYLIP format" },
    { value: "http://edamontology.org/format_1998", label: "PHYLIP sequential" },
    { value: "http://edamontology.org/format_1999", label: "scores format" },
    { value: "http://edamontology.org/format_2000", label: "selex" },
    { value: "http://edamontology.org/format_2001", label: "EMBOSS simple format" },
    { value: "http://edamontology.org/format_2002", label: "srs format" },
    { value: "http://edamontology.org/format_2003", label: "srspair" },
    { value: "http://edamontology.org/format_2004", label: "T-Coffee format" },
    { value: "http://edamontology.org/format_2005", label: "TreeCon-seq" },
    { value: "http://edamontology.org/format_2006", label: "Phylogenetic tree format" },
    { value: "http://edamontology.org/format_2013", label: "Biological pathway or network format" },
    { value: "http://edamontology.org/format_2014", label: "Sequence-profile alignment format" },
    { value: "http://edamontology.org/format_2017", label: "Amino acid index format" },
    { value: "http://edamontology.org/format_2020", label: "Article format" },
    { value: "http://edamontology.org/format_2021", label: "Text mining report format" },
    { value: "http://edamontology.org/format_2027", label: "Enzyme kinetics report format" },
    { value: "http://edamontology.org/format_2030", label: "Chemical data format" },
    { value: "http://edamontology.org/format_2031", label: "Gene annotation format" },
    { value: "http://edamontology.org/format_2032", label: "Workflow format" },
    { value: "http://edamontology.org/format_2033", label: "Tertiary structure format" },
    { value: "http://edamontology.org/format_2035", label: "Chemical formula format" },
    { value: "http://edamontology.org/format_2036", label: "Phylogenetic character data format" },
    { value: "http://edamontology.org/format_2037", label: "Phylogenetic continuous quantitative character format" },
    { value: "http://edamontology.org/format_2038", label: "Phylogenetic discrete states format" },
    { value: "http://edamontology.org/format_2039", label: "Phylogenetic tree report (cliques) format" },
    { value: "http://edamontology.org/format_2040", label: "Phylogenetic tree report (invariants) format" },
    { value: "http://edamontology.org/format_2049", label: "Phylogenetic tree report (tree distances) format" },
    { value: "http://edamontology.org/format_2052", label: "Protein family report format" },
    { value: "http://edamontology.org/format_2054", label: "Protein interaction format" },
    { value: "http://edamontology.org/format_2055", label: "Sequence assembly format" },
    { value: "http://edamontology.org/format_2056", label: "Microarray experiment data format" },
    { value: "http://edamontology.org/format_2057", label: "Sequence trace format" },
    { value: "http://edamontology.org/format_2058", label: "Gene expression report format" },
    { value: "http://edamontology.org/format_2060", label: "Map format" },
    { value: "http://edamontology.org/format_2061", label: "Nucleic acid features (primers) format" },
    { value: "http://edamontology.org/format_2062", label: "Protein report format" },
    { value: "http://edamontology.org/format_2064", label: "3D-1D scoring matrix format" },
    { value: "http://edamontology.org/format_2065", label: "Protein structure report (quality evaluation) format" },
    { value: "http://edamontology.org/format_2066", label: "Database hits (sequence) format" },
    { value: "http://edamontology.org/format_2067", label: "Sequence distance matrix format" },
    { value: "http://edamontology.org/format_2068", label: "Sequence motif format" },
    { value: "http://edamontology.org/format_2069", label: "Sequence profile format" },
    { value: "http://edamontology.org/format_2072", label: "Hidden Markov model format" },
    { value: "http://edamontology.org/format_2074", label: "Dirichlet distribution format" },
    { value: "http://edamontology.org/format_2075", label: "HMM emission and transition counts format" },
    { value: "http://edamontology.org/format_2076", label: "RNA secondary structure format" },
    { value: "http://edamontology.org/format_2077", label: "Protein secondary structure format" },
    { value: "http://edamontology.org/format_2078", label: "Sequence range format" },
    { value: "http://edamontology.org/format_2094", label: "pure" },
    { value: "http://edamontology.org/format_2095", label: "unpure" },
    { value: "http://edamontology.org/format_2096", label: "unambiguous sequence" },
    { value: "http://edamontology.org/format_2097", label: "ambiguous" },
    { value: "http://edamontology.org/format_2155", label: "Sequence features (repeats) format" },
    { value: "http://edamontology.org/format_2158", label: "Nucleic acid features (restriction sites) format" },
    { value: "http://edamontology.org/format_2170", label: "Sequence cluster format" },
    { value: "http://edamontology.org/format_2171", label: "Sequence cluster format (protein)" },
    { value: "http://edamontology.org/format_2172", label: "Sequence cluster format (nucleic acid)" },
    { value: "http://edamontology.org/format_2181", label: "EMBL-like (text)" },
    { value: "http://edamontology.org/format_2182", label: "FASTQ-like format (text)" },
    { value: "http://edamontology.org/format_2183", label: "EMBLXML" },
    { value: "http://edamontology.org/format_2184", label: "cdsxml" },
    { value: "http://edamontology.org/format_2185", label: "insdxml" },
    { value: "http://edamontology.org/format_2186", label: "geneseq" },
    { value: "http://edamontology.org/format_2187", label: "UniProt-like (text)" },
    { value: "http://edamontology.org/format_2194", label: "medline" },
    { value: "http://edamontology.org/format_2195", label: "Ontology format" },
    { value: "http://edamontology.org/format_2196", label: "OBO format" },
    { value: "http://edamontology.org/format_2197", label: "OWL format" },
    { value: "http://edamontology.org/format_2200", label: "FASTA-like (text)" },
    { value: "http://edamontology.org/format_2204", label: "EMBL format (XML)" },
    { value: "http://edamontology.org/format_2205", label: "GenBank-like format (text)" },
    { value: "http://edamontology.org/format_2206", label: "Sequence feature table format (text)" },
    { value: "http://edamontology.org/format_2304", label: "STRING entry format (XML)" },
    { value: "http://edamontology.org/format_2305", label: "GFF" },
    { value: "http://edamontology.org/format_2306", label: "GTF" },
    { value: "http://edamontology.org/format_2310", label: "FASTA-HTML" },
    { value: "http://edamontology.org/format_2311", label: "EMBL-HTML" },
    { value: "http://edamontology.org/format_2330", label: "Textual format" },
    { value: "http://edamontology.org/format_2331", label: "HTML" },
    { value: "http://edamontology.org/format_2332", label: "XML" },
    { value: "http://edamontology.org/format_2333", label: "Binary format" },
    { value: "http://edamontology.org/format_2350", label: "Format (by type of data)" },
    { value: "http://edamontology.org/format_2352", label: "BioXSD (XML)" },
    { value: "http://edamontology.org/format_2376", label: "RDF format" },
    { value: "http://edamontology.org/format_2532", label: "GenBank-HTML" },
    { value: "http://edamontology.org/format_2543", label: "EMBL-like format" },
    { value: "http://edamontology.org/format_2545", label: "FASTQ-like format" },
    { value: "http://edamontology.org/format_2546", label: "FASTA-like" },
    { value: "http://edamontology.org/format_2547", label: "uniprotkb-like format" },
    { value: "http://edamontology.org/format_2548", label: "Sequence feature table format" },
    { value: "http://edamontology.org/format_2549", label: "OBO" },
    { value: "http://edamontology.org/format_2550", label: "OBO-XML" },
    { value: "http://edamontology.org/format_2551", label: "Sequence record format (text)" },
    { value: "http://edamontology.org/format_2552", label: "Sequence record format (XML)" },
    { value: "http://edamontology.org/format_2553", label: "Sequence feature table format (XML)" },
    { value: "http://edamontology.org/format_2554", label: "Alignment format (text)" },
    { value: "http://edamontology.org/format_2555", label: "Alignment format (XML)" },
    { value: "http://edamontology.org/format_2556", label: "Phylogenetic tree format (text)" },
    { value: "http://edamontology.org/format_2557", label: "Phylogenetic tree format (XML)" },
    { value: "http://edamontology.org/format_2558", label: "EMBL-like (XML)" },
    { value: "http://edamontology.org/format_2559", label: "GenBank-like format" },
    { value: "http://edamontology.org/format_2561", label: "Sequence assembly format (text)" },
    { value: "http://edamontology.org/format_2566", label: "completely unambiguous" },
    { value: "http://edamontology.org/format_2567", label: "completely unambiguous pure" },
    { value: "http://edamontology.org/format_2568", label: "completely unambiguous pure nucleotide" },
    { value: "http://edamontology.org/format_2569", label: "completely unambiguous pure dna" },
    { value: "http://edamontology.org/format_2570", label: "completely unambiguous pure rna sequence" },
    { value: "http://edamontology.org/format_2571", label: "Raw sequence format" },
    { value: "http://edamontology.org/format_2572", label: "BAM" },
    { value: "http://edamontology.org/format_2573", label: "SAM" },
    { value: "http://edamontology.org/format_2585", label: "SBML" },
    { value: "http://edamontology.org/format_2607", label: "completely unambiguous pure protein" },
    { value: "http://edamontology.org/format_2848", label: "Bibliographic reference format" },
    { value: "http://edamontology.org/format_2919", label: "Sequence annotation track format" },
    { value: "http://edamontology.org/format_2920", label: "Alignment format (pair only)" },
    { value: "http://edamontology.org/format_2921", label: "Sequence variation annotation format" },
    { value: "http://edamontology.org/format_2922", label: "markx0 variant" },
    { value: "http://edamontology.org/format_2923", label: "mega variant" },
    { value: "http://edamontology.org/format_2924", label: "Phylip format variant" },
    { value: "http://edamontology.org/format_3000", label: "AB1" },
    { value: "http://edamontology.org/format_3001", label: "ACE" },
    { value: "http://edamontology.org/format_3003", label: "BED" },
    { value: "http://edamontology.org/format_3004", label: "bigBed" },
    { value: "http://edamontology.org/format_3005", label: "WIG" },
    { value: "http://edamontology.org/format_3006", label: "bigWig" },
    { value: "http://edamontology.org/format_3007", label: "PSL" },
    { value: "http://edamontology.org/format_3008", label: "MAF" },
    { value: "http://edamontology.org/format_3009", label: "2bit" },
    { value: "http://edamontology.org/format_3010", label: ".nib" },
    { value: "http://edamontology.org/format_3011", label: "genePred" },
    { value: "http://edamontology.org/format_3012", label: "pgSnp" },
    { value: "http://edamontology.org/format_3013", label: "axt" },
    { value: "http://edamontology.org/format_3014", label: "LAV" },
    { value: "http://edamontology.org/format_3015", label: "Pileup" },
    { value: "http://edamontology.org/format_3016", label: "VCF" },
    { value: "http://edamontology.org/format_3017", label: "SRF" },
    { value: "http://edamontology.org/format_3018", label: "ZTR" },
    { value: "http://edamontology.org/format_3019", label: "GVF" },
    { value: "http://edamontology.org/format_3020", label: "BCF" },
    { value: "http://edamontology.org/format_3033", label: "Matrix format" },
    { value: "http://edamontology.org/format_3097", label: "Protein domain classification format" },
    { value: "http://edamontology.org/format_3098", label: "Raw SCOP domain classification format" },
    { value: "http://edamontology.org/format_3099", label: "Raw CATH domain classification format" },
    { value: "http://edamontology.org/format_3100", label: "CATH domain report format" },
    { value: "http://edamontology.org/format_3155", label: "SBRML" },
    { value: "http://edamontology.org/format_3156", label: "BioPAX" },
    { value: "http://edamontology.org/format_3157", label: "EBI Application Result XML" },
    { value: "http://edamontology.org/format_3158", label: "PSI MI XML (MIF)" },
    { value: "http://edamontology.org/format_3159", label: "phyloXML" },
    { value: "http://edamontology.org/format_3160", label: "NeXML" },
    { value: "http://edamontology.org/format_3161", label: "MAGE-ML" },
    { value: "http://edamontology.org/format_3162", label: "MAGE-TAB" },
    { value: "http://edamontology.org/format_3163", label: "GCDML" },
    { value: "http://edamontology.org/format_3164", label: "GTrack" },
    { value: "http://edamontology.org/format_3166", label: "Biological pathway or network report format" },
    { value: "http://edamontology.org/format_3167", label: "Experiment annotation format" },
    { value: "http://edamontology.org/format_3235", label: "Cytoband format" },
    { value: "http://edamontology.org/format_3239", label: "CopasiML" },
    { value: "http://edamontology.org/format_3240", label: "CellML" },
    { value: "http://edamontology.org/format_3242", label: "PSI MI TAB (MITAB)" },
    { value: "http://edamontology.org/format_3243", label: "PSI-PAR" },
    { value: "http://edamontology.org/format_3244", label: "mzML" },
    { value: "http://edamontology.org/format_3245", label: "Mass spectrometry data format" },
    { value: "http://edamontology.org/format_3246", label: "TraML" },
    { value: "http://edamontology.org/format_3247", label: "mzIdentML" },
    { value: "http://edamontology.org/format_3248", label: "mzQuantML" },
    { value: "http://edamontology.org/format_3249", label: "GelML" },
    { value: "http://edamontology.org/format_3250", label: "spML" },
    { value: "http://edamontology.org/format_3252", label: "OWL Functional Syntax" },
    { value: "http://edamontology.org/format_3253", label: "Manchester OWL Syntax" },
    { value: "http://edamontology.org/format_3254", label: "KRSS2 Syntax" },
    { value: "http://edamontology.org/format_3255", label: "Turtle" },
    { value: "http://edamontology.org/format_3256", label: "N-Triples" },
    { value: "http://edamontology.org/format_3257", label: "Notation3" },
    { value: "http://edamontology.org/format_3261", label: "RDF/XML" },
    { value: "http://edamontology.org/format_3262", label: "OWL/XML" },
    { value: "http://edamontology.org/format_3281", label: "A2M" },
    { value: "http://edamontology.org/format_3284", label: "SFF" },
    { value: "http://edamontology.org/format_3285", label: "MAP" },
    { value: "http://edamontology.org/format_3286", label: "PED" },
    { value: "http://edamontology.org/format_3287", label: "Individual genetic data format" },
    { value: "http://edamontology.org/format_3288", label: "PED/MAP" },
    { value: "http://edamontology.org/format_3309", label: "CT" },
    { value: "http://edamontology.org/format_3310", label: "SS" },
    { value: "http://edamontology.org/format_3311", label: "RNAML" },
    { value: "http://edamontology.org/format_3312", label: "GDE" },
    { value: "http://edamontology.org/format_3313", label: "BLC" },
    { value: "http://edamontology.org/format_3326", label: "Data index format" },
    { value: "http://edamontology.org/format_3327", label: "BAI" },
    { value: "http://edamontology.org/format_3328", label: "HMMER2" },
    { value: "http://edamontology.org/format_3329", label: "HMMER3" },
    { value: "http://edamontology.org/format_3330", label: "PO" },
    { value: "http://edamontology.org/format_3331", label: "BLAST XML results format" },
    { value: "http://edamontology.org/format_3462", label: "CRAM" },
    { value: "http://edamontology.org/format_3464", label: "JSON" },
    { value: "http://edamontology.org/format_3466", label: "EPS" },
    { value: "http://edamontology.org/format_3467", label: "GIF" },
    { value: "http://edamontology.org/format_3468", label: "xls" },
    { value: "http://edamontology.org/format_3475", label: "TSV" },
    { value: "http://edamontology.org/format_3477", label: "Cytoscape input file format" },
    { value: "http://edamontology.org/format_3484", label: "ebwt" },
    { value: "http://edamontology.org/format_3485", label: "RSF" },
    { value: "http://edamontology.org/format_3486", label: "GCG format variant" },
    { value: "http://edamontology.org/format_3487", label: "BSML" },
    { value: "http://edamontology.org/format_3491", label: "ebwtl" },
    { value: "http://edamontology.org/format_3499", label: "Ensembl variation file format" },
    { value: "http://edamontology.org/format_3506", label: "docx" },
    { value: "http://edamontology.org/format_3507", label: "Document format" },
    { value: "http://edamontology.org/format_3508", label: "PDF" },
    { value: "http://edamontology.org/format_3547", label: "Image format" },
    { value: "http://edamontology.org/format_3548", label: "DICOM format" },
    { value: "http://edamontology.org/format_3549", label: "nii" },
    { value: "http://edamontology.org/format_3550", label: "mhd" },
    { value: "http://edamontology.org/format_3551", label: "nrrd" },
    { value: "http://edamontology.org/format_3554", label: "R file format" },
    { value: "http://edamontology.org/format_3555", label: "SPSS" },
    { value: "http://edamontology.org/format_3556", label: "MHTML" },
    { value: "http://edamontology.org/format_3578", label: "IDAT" },
    { value: "http://edamontology.org/format_3579", label: "JPG" },
    { value: "http://edamontology.org/format_3580", label: "rcc" },
    { value: "http://edamontology.org/format_3581", label: "arff" },
    { value: "http://edamontology.org/format_3582", label: "afg" },
    { value: "http://edamontology.org/format_3583", label: "bedgraph" },
    { value: "http://edamontology.org/format_3584", label: "bedstrict" },
    { value: "http://edamontology.org/format_3585", label: "bed6" },
    { value: "http://edamontology.org/format_3586", label: "bed12" },
    { value: "http://edamontology.org/format_3587", label: "chrominfo" },
    { value: "http://edamontology.org/format_3588", label: "customtrack" },
    { value: "http://edamontology.org/format_3589", label: "csfasta" },
    { value: "http://edamontology.org/format_3590", label: "HDF5" },
    { value: "http://edamontology.org/format_3591", label: "TIFF" },
    { value: "http://edamontology.org/format_3592", label: "BMP" },
    { value: "http://edamontology.org/format_3593", label: "im" },
    { value: "http://edamontology.org/format_3594", label: "pcd" },
    { value: "http://edamontology.org/format_3595", label: "pcx" },
    { value: "http://edamontology.org/format_3596", label: "ppm" },
    { value: "http://edamontology.org/format_3597", label: "psd" },
    { value: "http://edamontology.org/format_3598", label: "xbm" },
    { value: "http://edamontology.org/format_3599", label: "xpm" },
    { value: "http://edamontology.org/format_3600", label: "rgb" },
    { value: "http://edamontology.org/format_3601", label: "pbm" },
    { value: "http://edamontology.org/format_3602", label: "pgm" },
    { value: "http://edamontology.org/format_3603", label: "PNG" },
    { value: "http://edamontology.org/format_3604", label: "SVG" },
    { value: "http://edamontology.org/format_3605", label: "rast" },
    { value: "http://edamontology.org/format_3606", label: "Sequence quality report format (text)" },
    { value: "http://edamontology.org/format_3607", label: "qual" },
    { value: "http://edamontology.org/format_3608", label: "qualsolexa" },
    { value: "http://edamontology.org/format_3609", label: "qualillumina" },
    { value: "http://edamontology.org/format_3610", label: "qualsolid" },
    { value: "http://edamontology.org/format_3611", label: "qual454" },
    { value: "http://edamontology.org/format_3612", label: "ENCODE peak format" },
    { value: "http://edamontology.org/format_3613", label: "ENCODE narrow peak format" },
    { value: "http://edamontology.org/format_3614", label: "ENCODE broad peak format" },
    { value: "http://edamontology.org/format_3615", label: "bgzip" },
    { value: "http://edamontology.org/format_3616", label: "tabix" },
    { value: "http://edamontology.org/format_3617", label: "Graph format" },
    { value: "http://edamontology.org/format_3618", label: "xgmml" },
    { value: "http://edamontology.org/format_3619", label: "sif" },
    { value: "http://edamontology.org/format_3620", label: "xlsx" },
    { value: "http://edamontology.org/format_3621", label: "SQLite format" },
    { value: "http://edamontology.org/format_3622", label: "Gemini SQLite format" },
    { value: "http://edamontology.org/format_3624", label: "snpeffdb" },
    { value: "http://edamontology.org/format_3626", label: "MAT" },
    { value: "http://edamontology.org/format_3650", label: "netCDF" },
    { value: "http://edamontology.org/format_3651", label: "MGF" },
    { value: "http://edamontology.org/format_3652", label: "dta" },
    { value: "http://edamontology.org/format_3653", label: "pkl" },
    { value: "http://edamontology.org/format_3654", label: "mzXML" },
    { value: "http://edamontology.org/format_3655", label: "pepXML" },
    { value: "http://edamontology.org/format_3657", label: "GPML" },
    { value: "http://edamontology.org/format_3681", label: "mzTab" },
    { value: "http://edamontology.org/format_3682", label: "imzML metadata file" },
    { value: "http://edamontology.org/format_3683", label: "qcML" },
    { value: "http://edamontology.org/format_3684", label: "PRIDE XML" },
    { value: "http://edamontology.org/format_3685", label: "SED-ML" },
    { value: "http://edamontology.org/format_3686", label: "COMBINE OMEX" },
    { value: "http://edamontology.org/format_3687", label: "ISA-TAB" },
    { value: "http://edamontology.org/format_3688", label: "SBtab" },
    { value: "http://edamontology.org/format_3689", label: "BCML" },
    { value: "http://edamontology.org/format_3690", label: "BDML" },
    { value: "http://edamontology.org/format_3691", label: "BEL" },
    { value: "http://edamontology.org/format_3692", label: "SBGN-ML" },
    { value: "http://edamontology.org/format_3693", label: "AGP" },
    { value: "http://edamontology.org/format_3696", label: "PS" },
    { value: "http://edamontology.org/format_3698", label: "SRA format" },
    { value: "http://edamontology.org/format_3699", label: "VDB" },
    { value: "http://edamontology.org/format_3700", label: "Tabix index file format" },
    { value: "http://edamontology.org/format_3701", label: "Sequin format" },
    { value: "http://edamontology.org/format_3702", label: "MSF" },
    { value: "http://edamontology.org/format_3706", label: "Biodiversity data format" },
    { value: "http://edamontology.org/format_3708", label: "ABCD format" },
    { value: "http://edamontology.org/format_3709", label: "GCT/Res format" },
    { value: "http://edamontology.org/format_3710", label: "WIFF format" },
    { value: "http://edamontology.org/format_3711", label: "X!Tandem XML" },
    { value: "http://edamontology.org/format_3712", label: "Thermo RAW" },
    { value: "http://edamontology.org/format_3713", label: "Mascot .dat file" },
    { value: "http://edamontology.org/format_3714", label: "MaxQuant APL peaklist format" },
    { value: "http://edamontology.org/format_3725", label: "SBOL" },
    { value: "http://edamontology.org/format_3726", label: "PMML" },
    { value: "http://edamontology.org/format_3727", label: "OME-TIFF" },
    { value: "http://edamontology.org/format_3728", label: "LocARNA PP" },
    { value: "http://edamontology.org/format_3729", label: "dbGaP format" },
    { value: "http://edamontology.org/format_3746", label: "BIOM format" },
    { value: "http://edamontology.org/format_3747", label: "protXML" },
    { value: "http://edamontology.org/format_3748", label: "Linked data format" },
    { value: "http://edamontology.org/format_3749", label: "JSON-LD" },
    { value: "http://edamontology.org/format_3750", label: "YAML" },
    { value: "http://edamontology.org/format_3751", label: "DSV" },
    { value: "http://edamontology.org/format_3752", label: "CSV" },
    { value: "http://edamontology.org/format_3758", label: "SEQUEST .out file" },
    { value: "http://edamontology.org/format_3764", label: "idXML" },
    { value: "http://edamontology.org/format_3765", label: "KNIME datatable format" },
    { value: "http://edamontology.org/format_3770", label: "UniProtKB XML" },
    { value: "http://edamontology.org/format_3771", label: "UniProtKB RDF" },
    { value: "http://edamontology.org/format_3772", label: "BioJSON (BioXSD)" },
    { value: "http://edamontology.org/format_3773", label: "BioYAML" },
    { value: "http://edamontology.org/format_3774", label: "BioJSON (Jalview)" },
    { value: "http://edamontology.org/format_3775", label: "GSuite" },
    { value: "http://edamontology.org/format_3776", label: "BTrack" },
    { value: "http://edamontology.org/format_3777", label: "MCPD" },
    { value: "http://edamontology.org/format_3780", label: "Annotated text format" },
    { value: "http://edamontology.org/format_3781", label: "PubAnnotation format" },
    { value: "http://edamontology.org/format_3782", label: "BioC" },
    { value: "http://edamontology.org/format_3783", label: "PubTator format" },
    { value: "http://edamontology.org/format_3784", label: "Open Annotation format" },
    { value: "http://edamontology.org/format_3785", label: "BioNLP Shared Task format" },
    { value: "http://edamontology.org/format_3787", label: "Query language" },
    { value: "http://edamontology.org/format_3788", label: "SQL" },
    { value: "http://edamontology.org/format_3789", label: "XQuery" },
    { value: "http://edamontology.org/format_3790", label: "SPARQL" },
    { value: "http://edamontology.org/format_3804", label: "xsd" },
    { value: "http://edamontology.org/format_3811", label: "XMFA" },
    { value: "http://edamontology.org/format_3812", label: "GEN" },
    { value: "http://edamontology.org/format_3813", label: "SAMPLE file format" },
    { value: "http://edamontology.org/format_3814", label: "SDF" },
    { value: "http://edamontology.org/format_3815", label: "Molfile" },
    { value: "http://edamontology.org/format_3816", label: "Mol2" },
    { value: "http://edamontology.org/format_3817", label: "latex" },
    { value: "http://edamontology.org/format_3818", label: "ELAND format" },
    { value: "http://edamontology.org/format_3819", label: "Relaxed PHYLIP Interleaved" },
    { value: "http://edamontology.org/format_3820", label: "Relaxed PHYLIP Sequential" },
    { value: "http://edamontology.org/format_3821", label: "VisML" },
    { value: "http://edamontology.org/format_3822", label: "GML" },
    { value: "http://edamontology.org/format_3823", label: "FASTG" },
    { value: "http://edamontology.org/format_3824", label: "NMR data format" },
    { value: "http://edamontology.org/format_3825", label: "nmrML" },
    { value: "http://edamontology.org/format_3826", label: "proBAM" },
    { value: "http://edamontology.org/format_3827", label: "proBED" },
    { value: "http://edamontology.org/format_3828", label: "Raw microarray data format" },
    { value: "http://edamontology.org/format_3829", label: "GPR" },
    { value: "http://edamontology.org/format_3830", label: "ARB" },
    { value: "http://edamontology.org/format_3832", label: "consensusXML" },
    { value: "http://edamontology.org/format_3833", label: "featureXML" },
    { value: "http://edamontology.org/format_3834", label: "mzData" },
    { value: "http://edamontology.org/format_3835", label: "TIDE TXT" },
    { value: "http://edamontology.org/format_3836", label: "BLAST XML v2 results format" },
    { value: "http://edamontology.org/format_3838", label: "pptx" },
    { value: "http://edamontology.org/format_3839", label: "ibd" },
    { value: "http://edamontology.org/format_3841", label: "NLP format" },
    { value: "http://edamontology.org/format_3843", label: "BEAST" },
    { value: "http://edamontology.org/format_3844", label: "Chado-XML" },
    { value: "http://edamontology.org/format_3845", label: "HSAML" },
    { value: "http://edamontology.org/format_3846", label: "InterProScan XML" },
    { value: "http://edamontology.org/format_3847", label: "KGML" },
    { value: "http://edamontology.org/format_3848", label: "PubMed XML" },
    { value: "http://edamontology.org/format_3849", label: "MSAML" },
    { value: "http://edamontology.org/format_3850", label: "OrthoXML" },
    { value: "http://edamontology.org/format_3851", label: "PSDML" },
    { value: "http://edamontology.org/format_3852", label: "SeqXML" },
    { value: "http://edamontology.org/format_3853", label: "UniParc XML" },
    { value: "http://edamontology.org/format_3854", label: "UniRef XML" },
    { value: "http://edamontology.org/format_3857", label: "CWL" },
    { value: "http://edamontology.org/format_3858", label: "Waters RAW" },
    { value: "http://edamontology.org/format_3859", label: "JCAMP-DX" },
    { value: "http://edamontology.org/format_3862", label: "NLP annotation format" },
    { value: "http://edamontology.org/format_3863", label: "NLP corpus format" },
    { value: "http://edamontology.org/format_3864", label: "mirGFF3" },
    { value: "http://edamontology.org/format_3865", label: "RNA annotation format" },
    { value: "http://edamontology.org/format_3866", label: "Trajectory format" },
    { value: "http://edamontology.org/format_3867", label: "Trajectory format (binary)" },
    { value: "http://edamontology.org/format_3868", label: "Trajectory format (text)" },
    { value: "http://edamontology.org/format_3873", label: "HDF" },
    { value: "http://edamontology.org/format_3874", label: "PCAzip" },
    { value: "http://edamontology.org/format_3875", label: "XTC" },
    { value: "http://edamontology.org/format_3876", label: "TNG" },
    { value: "http://edamontology.org/format_3877", label: "XYZ" },
    { value: "http://edamontology.org/format_3878", label: "mdcrd" },
    { value: "http://edamontology.org/format_3879", label: "Topology format" },
    { value: "http://edamontology.org/format_3880", label: "GROMACS top" },
    { value: "http://edamontology.org/format_3881", label: "AMBER top" },
    { value: "http://edamontology.org/format_3882", label: "PSF" },
    { value: "http://edamontology.org/format_3883", label: "GROMACS itp" },
    { value: "http://edamontology.org/format_3885", label: "BinPos" },
    { value: "http://edamontology.org/format_3886", label: "RST" },
    { value: "http://edamontology.org/format_3887", label: "CHARMM rtf" },
    { value: "http://edamontology.org/format_3888", label: "AMBER frcmod" },
    { value: "http://edamontology.org/format_3906", label: "NMReDATA" },
    { value: "http://edamontology.org/format_3909", label: "BpForms" },
    { value: "http://edamontology.org/format_3911", label: "msh" }
];

export default options;