import {
  faBars,
  faCalendarPlus,
  faHammer,
  faQuoteLeft,
  faRunning,
  faUserEdit
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useState } from 'react';

import Link from 'next/link';

import styles from '../../styles/view.module.css';

import SectionSelector from './SectionSelector';
import SidePanelTools from './SidePanelTools';

import getConfig from "next/config";
const { publicRuntimeConfig } = getConfig();

/**
 * The side panel that has information about the object.
 * Has buttons for downloading, sharing, citing and deleting along with page sections.
 * 
 * @param {Any} properties Information from the parent component.
 */
export default function SidePanel(properties) {
  const metadata = properties.metadata;
  const [translation, setTranslation] = useState(0);
  const date = metadata.created.replace('T', ' ').replace('Z', '');

  return (
    <div className={translation === 0 ? styles.sidepanelcontaineropen : styles.sidepanelcontainercollapse}>
      <div className={styles.sidepanel} style={{ transform: `translateX(-${translation}rem)`, transition: "transform 0.3s" }}>
        <div className={styles.headercontainer}>
          <div className={styles.headeroverflowcontainer}>
            <h2 className={styles.title}>{metadata.name}</h2>
            <Link href = {`${publicRuntimeConfig.backend}/search/displayId='${metadata.displayId}'&`}>
              <a title = "Find all records with the same identifier" target = "_blank">
                <div className={styles.displayId}>({metadata.displayId})</div>
              </a>
            </Link>
          </div>
          <div
            className={styles.panelbutton}
            role="button"
            onClick={() => {
              translation == 18 ? setTranslation(0) : setTranslation(18);
            }}
          >
            <FontAwesomeIcon icon={faBars} size="1x" />
          </div>
        </div>
        <div style={{ transform: `translateX(-${translation === 18 ? 2.5 : 0}rem)`, transition: "transform 0.3s" }}>
          <SidePanelTools
            creator={metadata.creator}
            type={properties.type}
            displayId={metadata.displayId}
            name={metadata.name}
            url={properties.uri.replace('https://synbiohub.org', '')}
          />
          <div className={styles.infocontainer}>
            <Info
              icon={faQuoteLeft}
              label="Source"
              title={metadata.wasDerivedFrom}
              link={metadata.wasDerivedFrom}
            />
            <Info
              icon={faHammer}
              label="Generated By"
              title={metadata.wasGeneratedBy}
              link={metadata.wasGeneratedBy}
            />
            <Info
              icon={faUserEdit}
              label="Creator"
              title={metadata.creator}
              link={`${publicRuntimeConfig.backend}/user/${metadata.creator.replace(" ", "")}`}
            />
            <Info
              icon={faCalendarPlus}
              label="Created"
              title={date}
              link={`${publicRuntimeConfig.backend}/search/createdBefore=${date.substring(0, date.lastIndexOf("-") + 3)}&createdAfter=${date.substring(0, date.lastIndexOf("-") + 3)}&`}
            />
            <Info
              icon={faRunning}
              label="Persistent Identity"
              title={metadata.persistentIdentity}
              link={properties.uri}
            />
          </div>
          <SectionSelector pagesInfo={properties.pagesInfo} />
        </div>
      </div>
    </div>
  );
}

/**
 * Component container for displaying metadata information about the object.
 * 
 * @param {Any} properties Information from the parent component.
 */
function Info(properties) {
  //If the metadata doesn't contain the title nothing should be rendered.
  if (!properties.title) return null;

  return (
    <Link href={properties.link}>
      <a target="_blank">
        <div className={styles.info}>
          <div className={styles.infoheader}>
            <div className={styles.infoiconcontainer}>
              <FontAwesomeIcon
                icon={properties.icon}
                size="1x"
                className={styles.infoicon}
              />
            </div>
            <div className={styles.infolabel}>{properties.label}</div>
          </div>
          <div className={styles.infotitle}>{properties.title}</div>
        </div>
      </a>
    </Link>
  );
}
