PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
CONSTRUCT {?s ?p ?o}  WHERE {
    {
        SELECT ?s WHERE {
             ?s sbh:topLevel <$uri>.
        }
        ORDER BY ?s
    }
    ?s ?p ?o
}
LIMIT 10000
OFFSET $offset