ALTER TABLE Users
ADD COLUMN graph_uri VARCHAR(128);

ALTER TABLE Users
ADD COLUMN is_admin BOOLEAN DEFAULT FALSE;

ALTER TABLE Users
ADD COLUMN is_curator BOOLEAN DEFAULT FALSE;

ALTER TABLE Users
ADD COLUMN is_member BOOLEAN DEFAULT FALSE;