server:
  port : 6789
  tomcat:
    relaxed-path-chars: ['<','>']
    relaxed-query-chars: ['<','>']
spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:./data/sbhdb
#    username: sa
#    password:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/synbiohub
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver


#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#      use-new-id-generator-mappings: false
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
#  h2:
#    console:
#      enabled: true
logging:
  file:
    path: ./data

synbiohub:
  firstLaunch: true

plugin:
  external:
    testserver:
      login: http://localhost:8104/loggedinAPI
      logout: http://localhost:8104/logoutAPI
      refresh: http://localhost:8104/refresh
      status: http://localhost:8104/status