server:
  port : 6789
  tomcat:
    relaxed-path-chars: ['<','>']
    relaxed-query-chars: ['<','>']
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/sbhdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
logging:
  file:
    path: ./data
synbiohub:
  firstLaunch: true
plugin:
  external:
    testserver:
      login: http://localhost:8104/loggedinAPI
      logout: http://localhost:8104/logoutAPI
      refresh: http://localhost:8104/refresh
      status: http://localhost:8104/status

jwt:
  private.key: classpath:app.priv
  public.key: classpath:app.pub

roleToEndpointPermissions:
  USER: ["/profile", "/do_logout", "/submit", "/rootCollections", "/setup", "/login", "/register", "/search", "/search/**", "/searchCount", "/searchCount/**", "/twins", "/uses", "/similar", "/sbol", "/sbolnr", "/metadata", "/gb", "/fasta", "/gff", "/download", "/public/**", "/sparql", "/ComponentDefinition/**", "/**/count", "/count"]
  CURATOR: ["/makePublic"]
  ADMIN: ['/admin/sparql', '/admin', '/admin/virtuoso', '/admin/graphs', '/admin/log', '/admin/mail', '/admin/plugins', '/admin/savePlugin', '/admin/deletePlugin', '/admin/registries', '/admin/saveRegistry', '/admin/deleteRegistry', '/admin/setAdministratorEmail', '/admin/retrieveFromWebOfRegistries', '/admin/federate', '/admin/remotes', '/admin/saveRemote', '/admin/deleteRemote', '/admin/explorerlog', '/admin/explorer', '/admin/explorerUpdateIndex', '/admin/theme', '/admin/users', '/admin/newUser', '/admin/updateUser', '/admin/deleteUser']
