server:
  port : 6789
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/sbhdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
logging:
  file:
    path: ./data
