import styles from '../../styles/defaulttable.module.css';

export default function Status() {
  return (
    <div className={styles.statuscontainer}>
      <table className={styles.table}>
        <tbody>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
          <tr>
            <td>Platform</td>
            <td>
              <code>Code</code>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
