name: Build and push docker images

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    name: Build frontend image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
    - name: Build the Docker image for the frontend
      run: |
        docker build ./frontend --tag synbiohub/sbh3frontend:snapshot
    - uses: azure/docker-login@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the frontend image to Docker Hub
      run: |
        docker push synbiohub/sbh3frontend:snapshot
