name: Test testing

on: push

jobs:
  build: 
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source tree
    - uses: nick-invision/retry@v1
      name: Build docker image
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: docker build . --file backend/Dockerfile --tag synbiohub/sbh3backend:snapshot
    - name: Package image
      run: |
        docker save synbiohub/synbiohub3:snapshot | gzip > sbh.tar.gz
    - uses: actions/upload-artifact@v2
      name: Upload Docker image
      with:
        name: sbh-image
        path: sbh.tar.gz
  sboltests:
    name: SBOL Test Suite
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source tree
    - uses: actions/download-artifact@v2
      name: Download Docker image
      with:
        name: sbh-image
    - name: Import saved Docker image
      run: |
        cat sbh.tar.gz | docker load synbiohub/synbiohub3:snapshot
    - uses: actions/setup-python@v1
      name: Install Python 
      with:
        python-version: '3.6' # To match the one in Travis
    - name: Install test dependencies
      run: |
        pip install -r tests/test_requirements.txt
    - uses: nick-invision/retry@v1
      name: Run test suite
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: tests/sbolsuite.sh
  sbhtests:
    name: SynBioHub Test Suite
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source tree
    - uses: actions/download-artifact@v2
      name: Download Docker image
      with:
        name: sbh-image
    - name: Import saved Docker image
      run: |
        cat sbh.tar.gz | docker load synbiohub/synbiohub3:snapshot
    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.6' # To match the one in Travis
    - name: Install test dependencies
      run: |
        pip install -r tests/test_requirements.txt
    - name: Run tests
      run: |
        tests/test.sh 
